export const DETAIL_ADD_DATA = "DETAIL_ADD_DATA";
export const DETAIL_START_LOADING = "DETAIL_START_LOADING";
export const DETAIL_STOP_LOADING = "DETAIL_STOP_LOADING";
export const GRID_ADD_DATA = "GRID_ADD_DATA";
export const GRID_FILTER = "GRID_FILTER";
export const GRID_START_LOADING = "GRID_START_LOADING";
export const GRID_STOP_LOADING = "GRID_STOP_LOADING";
export const GRID_TOGGLE_ACTIVE = "GRID_TOGGLE_ACTIVE";